`.unwrap()`減らした
mehm8128/mini-git pull request #8
Opened 2024-01-16 13:49 UTC by H1rono

close #2

2024-01-18 11:07 UTC, mehm8128 requested changes
:kansya_kansya:
1箇所デグレしてたので確認してほしいです:pray:

2024-01-18 11:07 UTC, mehm8128 commented on src/command/add.rs
> -    };
これ、`.git/index`ファイルが存在しないのはエラーではなくて普通にありえることとして(そのまま処理を続けたい)処理書いてたのでエラーっぽく処理しちゃうとまずそう(実際にやってみると`init`->`add .`でエラーになっちゃう)

関連箇所(既にentriesがあったら(≒`.git/index`があったら)既にあるやつと新しいのをいい感じにマージして、まだなかったら`merged_entries`を`new_entries`とする、みたいな感じ)
https://github.com/mehm8128/mini-git/pull/8/files#diff-59b1c73329476a374842d08c3b5221e063d2683fd804fa5676776ed71e4a0929L237-L240

2024-01-18 11:07 UTC, mehm8128 commented on src/command/add.rs
>              let path = entry.path();
僕が書いた時点でこうなってたからこれでいいなら僕が悪いんだけど、これで十分な気がした(なんか問題あるかな)
```suggestion
            let path = entry?.path();
```

2024-01-19 12:31 UTC, mehm8128 commented
mainに変更入れたらconflictも起こっちゃったので直してほしいです🙏

2024-01-19 13:58 UTC, H1rono commented on src/command/add.rs
>              let path = entry.path();
問題ないです、それにしときます

2024-01-19 14:19 UTC, mehm8128 commented
https://github.com/mehm8128/mini-git/pull/8#discussion_r1457272303
これ見逃されてそう？

2024-01-19 16:21 UTC, H1rono commented
明日

2024-01-21 02:57 UTC, mehm8128 approved these changes
よさそうです、ありがとうございます！

2024-01-21 02:57 UTC, merged